# -*- coding:utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import abc
from typing import Optional, Dict

from core.domain.entity import Session
from core.dto import ValidateCardRes, AuthRes, GetBalanceRes, DepositRes, WithdrawRes
from core.repo.bank_repo import AbstractBankRepository
from core.repo.session_repo import AbstractSessionRepository
from core.util import ChipDecryptor


class ATMUseCase(object):
    _instance: Optional[ATMUseCase]
    chip_decryptor: ChipDecryptor
    session_repo: AbstractSessionRepository
    bank_repo: AbstractBankRepository
    cash_bin: AbstactCashBinUseCase
    # builder: Builder

    @classmethod
    def get_instance(cls) -> ATMUseCase: ...
    def __init__(self) -> None: ...
    def validate_card(self, encrypted_card_info: str) -> ValidateCardRes: ...
    def auth(self, pin: str, session_id: str) -> AuthRes: ...
    def get_balance(self, account_id: str, session_id: str) -> GetBalanceRes: ...
    def deposit(self, account_id: str, session_id: str, amount: int) -> DepositRes: ...
    def withdraw(self, account_id: str, session_id: str, amount: int) -> WithdrawRes: ...

    # def deposit(self, account_id: str, session_id: str, amount: int) -> DepositRes: ...
    # def withdraw(self, account_id: str, session_id: str, amount: int) -> WithdrawRes: ...


# TODO: move to different file
class AbstactCashBinUseCase(object):
    __metaclass__ = abc.ABCMeta

    @abc.abstractmethod
    def get_total(self) -> int: ...
    @abc.abstractmethod
    def get_max_deposit(self) -> int: ...
    @abc.abstractmethod
    def add(self, amount: int) -> int: ...
    @abc.abstractmethod
    def remove(self, amount: int) -> int: ...

class FakeCashBinUseCase(AbstactCashBinUseCase):
    _total: int
    _capacity: int
    def __init__(self, init_amount: int = 1000000) -> None: ...
    def get_total(self) -> int: ...
    def get_max_deposit(self) -> int: ...
    def add(self, amount: int) -> int: ...
    def remove(self, amount: int) -> int: ...